name: Deploy to pages on trunk

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:17-alpine
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: "Install deps"
      run: |
        apk add python3
        yarn

    - name: "yarn deploy"
      run: |
        GIT_USER=ChiaAutomation USE_SSH=true yarn deploy
