name: Deploy to pages on trunk

on:
  push:
    branches:
      - '!main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:17-alpine
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: "Install deps"
      run: |
        npm install --global yarn
        yarn

    - name: "yarn deploy"
      run: |
        GIT_USER=ChiaAutomation USE_SSH=true yarn deploy
